cookie:
  expiry_days: 30
  key: '5fd924625f6ab16a19cc9807c7c506ae1813490e4ba675f843d5a10e0baacdb8'
  name: 'game-voting-app-login'
credentials:
  usernames:
    user:
      email: null
      name: null
      password: null
      